mapbox/ios-sdk-examples

- LICENSE.md
Dedicate this repository to the public domain via CC0: shorter than the WTFPL and sweeter than `HKQuantityTypeIdentifierDietarySugar`.
Fixes #62.
/cc @tmcw @kathleenlu09
> Relinquish rights to code herein

- Examples/ObjectiveC/RuntimeAddLineExample.m
- Examples/ObjectiveC/RuntimeAnimateLineExample.m
- Examples/ObjectiveC/RuntimeCircleStylesExample.m
- Examples/ObjectiveC/RuntimeMultipleAnnotationsExample.m
- Examples/Swift/RuntimeAddLineExample.swift
- Examples/Swift/RuntimeAnimateLineExample.swift
- Examples/Swift/RuntimeCircleStylesExample.swift
- Examples/Swift/RuntimeMultipleAnnotationsExample.swift
Switched `MGLStyleFunction`s to `MGLCameraStyleFunction`.
Did not update these examples to use DDS.
> Update RTS examples for 3.5.0

- Examples/ObjectiveC/DrawingAGeoJSONLineExample.m
- Examples/Swift/DrawingAGeoJSONLineExample.swift
Modified the example to use the MGLShape factory method introduced in v3.4.0 instead of manually parsing GeoJSON serialized as Foundation collections.
/cc @friedbunny
> Simplified “Drawing a GeoJSON line”

- .github/ISSUE_TEMPLATE.md
- README.md
This repo is not for asking Mapbox iOS SDK implementation questions, so add links to places where developers _can_ find help.
/cc @mapbox/ios
> Clarify the purpose of this repo

- Podfile
- Podfile.lock
> Bumped podfile for v3.5.2

- .gitignore
- Examples.xcodeproj/project.pbxproj
- Examples/Info.plist
- fastlane/Appfile
- fastlane/Fastfile
Setting up a Bitrise workflow that deploys to TestFlight on every commit to `master`.
/cc @jmkiley @captainbarbosa
> Add fastlane TestFlight infrastructure

- Examples/ObjectiveC/BlockingGesturesDelegateExample.m
- Examples/ObjectiveC/CameraFlyToExample.m
- Examples/ObjectiveC/DDSLayerSelectionExample.m
- Examples/ObjectiveC/RuntimeAnimateLineExample.m
- Examples/Swift/AnnotationViewMultipleExample.swift
- Examples/Swift/BlockingGesturesDelegateExample.swift
- Examples/Swift/UserTrackingModesExample.swift
Small changes to indentation, punctuation, wording, and such.
/cc @jmkiley @captainbarbosa
> Tweak wording and spacing

- Examples/ObjectiveC/ExtrusionsExample.h
- Examples/ObjectiveC/ExtrusionsExample.m
- Examples/ObjectiveC/LightExample.h
- Examples/ObjectiveC/LightExample.m
- Examples/Swift/ExtrusionsExample.swift
Removed the Xcode header comments. 😳
> Removed headers

- Examples/Assets.xcassets/AppIcon.appiconset/Contents.json
- Examples/ObjectiveC/FillPatternExample.m
- Examples/Swift/FillPatternExample.swift
Addresses #104 and comments on #94 by improving the fill pattern example.
cc @friedbunny
> Additional improvements to fill pattern example

- Podfile
- Podfile.lock
> Bump to Mapbox iOS SDK v3.6.1

- Podfile
- Podfile.lock
https://github.com/mapbox/mapbox-gl-native/releases/tag/ios-v3.6.3
/cc @captainbarbosa @jmkiley
> Bump to Mapbox iOS SDK v3.6.3

- Examples/Examples.h
Some minor updates to the instructions for adding a new example.
> Clarify instructions to add new examples

- Examples.xcodeproj/project.pbxproj
- Examples/Examples.h
- Examples/Examples.m
- Examples/ObjectiveC/Headers/SwitchStylesExample.h
- Examples/ObjectiveC/SwitchStylesExample.m
- Examples/Swift/SwitchStylesExample.swift
New example to switch between map styles, similar to the [Mapbox GL JS](https://www.mapbox.com/mapbox-gl-js/example/setstyle/) counterpart.
> Switch between styles example

- Examples/ObjectiveC/UserTrackingModesExample.m
- Examples/Swift/UserTrackingModesExample.swift
Pulls https://github.com/mapbox/ios-sdk-examples/issues/7 across the finish line 🏁
> New example: switch between user tracking modes

- Examples/Examples.h
- Examples/Examples.m
- Examples/ExamplesTableViewController.m
- Examples/Main.storyboard
Per https://github.com/mapbox/ios-sdk-examples/issues/166
> [WIP]Example list should be better organized and more friendly

- Examples/Files/third_party_vector_style.json
- Examples/ObjectiveC/ThirdPartyVectorStyleExample.m
- Examples/Swift/ThirdPartyVectorStyleExample.swift
- Podfile.lock
> Account for min/max zoom in vector tile source example

- Examples.xcodeproj/project.pbxproj
- Examples.xcodeproj/xcshareddata/xcschemes/Examples.xcscheme
- Examples/Examples.h
- Examples/Examples.m
- Examples/ObjectiveC/Headers/HeatmapExample.h
- Examples/ObjectiveC/HeatmapExample.m
- Examples/Swift/HeatmapExample.swift
- Podfile.lock
Work in progress example that shows how to add and style a heatmap. There are some circular gaps in the example on simulator, but they do not appear on device.
To Do:
Addresses #145
> Heatmap example

- Examples/ObjectiveC/BuildingsExample.m
- Examples/Swift/BuildingsExample.swift
- Podfile.lock
> Updated building in "Display 3D Buildings" example

- Podfile
- Podfile.lock
> Update podspecs to 4.1.1.

- .swiftlint.yml
- Examples.xcodeproj/project.pbxproj
- Examples/ObjectiveC/PolygonPatternExample.m
> Minor cleanup stemming from ios-v4.4.0-alpha.2 QA

- DocsCode/NavigationTutorial/NavigationTutorialViewController.m
- Examples.xcodeproj/project.pbxproj
- Podfile
- Podfile.lock
Upgraded to navigation SDK v0.21.0.
/cc @friedbunny
> Navigation SDK v0.21.0

- Podfile
- Podfile.lock
Split out of #216.
/cc @julianrex @captainbarbosa
> Update for Xcode 10

- Examples/ObjectiveC/FeatureSelectionExample.m
- Examples/Swift/FeatureSelectionExample.swift
Forgot to update the links in the code comments from https://github.com/mapbox/ios-sdk-examples/pull/249
> Update to v4.7.0, pt II

- Podfile
- Podfile.lock
Upgraded to navigation SDK v0.27.0.
/cc @frederoni @JThramer
> Navigation SDK v0.27.0

- Examples/ObjectiveC/DDSCircleLayerExample.m
- Examples/ObjectiveC/PolygonPatternExample.m
- Examples/Swift/DDSCircleLayerExample.swift
- Examples/Swift/PolygonPatternExample.swift
🚧 This PR updates links to the API documentation to match the new URL structure. (Ref mapbox/api-documentation#590) Do not merge until API documentation changes land. 🚧
@captainbarbosa to review please 🙏
cc @mapbox/docs
> [DNM] Updates links to API documentation

- README.md
Updates documentation links to new URLs.
> Update documentation links in Readme

- Examples/Examples.m
- Examples/ObjectiveC/SelectFeatureExample.m
- Examples/Swift/SelectFeatureExample.swift
> Update SelectFeatureExample to use a more compatible layer

- DocsCode/NavigationTutorial/NavigationTutorialViewController.m
- Podfile
- Podfile.lock
Upgraded to navigation SDK v0.29.0.
/cc @mapbox/navigation-ios
> Navigation SDK v0.29.0

- Examples/ObjectiveC/LineStyleLayerExample.m
> Fix Objective-C LineStyleLayerExample

- Examples/ObjectiveC/RasterImageryExample.m
- Examples/ObjectiveC/ShowHideLayerExample.m
- Examples/ObjectiveC/UserTrackingModesExample.m
- Examples/Swift/RasterImageryExample.swift
- Examples/Swift/ShowHideLayerExample.swift
- Examples/Swift/UserTrackingModesExample.swift
> Update examples for safe area

- Podfile
- Podfile.lock
Upgraded to navigation SDK v0.30.0.
/cc @mapbox/navigation-ios
> Navigation SDK v0.30.0

- Examples.xcodeproj/project.pbxproj
- Podfile
- Podfile.lock
Bumps the sdk podspec to `4.10.0-beta.3.`, merges into #278.
> Updates pod sdk version to 4.10.0-beta.3.

- Examples.xcodeproj/project.pbxproj
- Examples/Examples.h
- Examples/Examples.m
- Examples/Files/text-format.json
- Examples/ObjectiveC/Headers/TextFormattingExample.h
- Examples/ObjectiveC/TextFormattingExample.m
- Examples/Swift/TextFormattingExample.swift
> [ios] Add example for formatting expressions.

- Podfile
- Podfile.lock
Upgraded to navigation SDK v0.31.0.
/cc @mapbox/navigation-ios
> Navigation SDK v0.31.0

- Examples.xcodeproj/project.pbxproj
- Examples.xcodeproj/xcshareddata/xcschemes/DocsCode.xcscheme
- Examples.xcodeproj/xcshareddata/xcschemes/Examples.xcscheme
- Podfile
- Podfile.lock
Upgraded to navigation SDK v0.32.0. Also updated the Xcode project to the settings recommended by Xcode 10.2.
/cc @frederoni @friedbunny
> Navigation SDK v0.32.0

- Podfile
- Podfile.lock
Upgraded to navigation SDK v0.33.0.
/cc @mapbox/navigation-ios
> Navigation SDK v0.33.0

- DEPLOYMENT.md
> [fastlane] Add environment variables tip to deployment doc

- Examples.xcodeproj/project.pbxproj
- Examples/ObjectiveC/UserTrackingModesExample.m
- Examples/Swift/CameraAnimationExample.swift
- Examples/Swift/DraggableAnnotationViewExample.swift
- Examples/Swift/SwitchStylesExample.swift
- Examples/Swift/TextFormattingExample.swift
- Examples/Swift/UserLocationAnnotationExample.swift
- Examples/Swift/UserTrackingModesExample.swift
- Examples/Swift/WebAPIDataExample.swift
Migrating to Swift 5 was smooth, though requiring `@unknown default` for exhaustive `enum`s feels a bit excessive. More on that in https://github.com/mapbox/mapbox-gl-native/issues/14787.
/cc @mapbox/maps-ios
> Update to Swift 5

- Examples.xcodeproj/project.pbxproj
- Examples/ObjectiveC/UserTrackingModesExample.m
- Examples/Swift/UserTrackingModesExample.swift
Fixes #213, where the user tracking mode button would not update when the user tracking mode changed without a button push.
/cc @captainbarbosa
> [UserTrackingModesExample] Fix button updates

- Examples/ObjectiveC/UserTrackingModesExample.m
- Examples/Swift/UserTrackingModesExample.swift
> UserTrackingModesExample: enable user heading indicator and simplify constraints

- codecov.yml
Fixes #332 
This increases the threshold for failure to 2%.
> Increase CodeCov threshold

- Examples/Files/metro-line.geojson
- Examples/ObjectiveC/MultipleShapesExample.m
- Examples/Swift/MultipleShapesExample.swift
Now shows three shapes (point, line, polygon), cleans up GeoJSON, and makes things Swiftier.
> 🧹 Clean up MultipleShapesExample

- Examples.xcodeproj/project.pbxproj
- Podfile
- Podfile.lock
> Update for Maps SDK for iOS v5.3.1

- Examples.xcodeproj/project.pbxproj
- Podfile
- Podfile.lock
Ongoing commits for release Sangria 🍷 (v5.5.0)
> Update Maps SDK version for v5.5.0

- Examples/ObjectiveC/BuildingLightExample.m
- Examples/ObjectiveC/RasterImageryExample.m
- Examples/Swift/BuildingLightExample.swift
- Examples/Swift/RasterImageryExample.swift
Resolves #375 by suppressing change events.
> Change slider configuration to non-continuous in order to suppress change events.

- Examples.xcodeproj/project.pbxproj
- Podfile
- Podfile.lock
Ongoing release bumps for the v5.6.0 release series.
> Update Maps SDK for ios-v5.6.0 (release-tequila)

- Examples.xcodeproj/project.pbxproj
- Podfile
- Podfile.lock
> Bump to 5.6.1

- Examples.xcodeproj/project.pbxproj
- Examples/ObjectiveC/StaticSnapshotExample.m
- Examples/Swift/StaticSnapshotExample.swift
- Podfile
- Podfile.lock
This PR is for testing v5.8.0.
> Maps SDK v5.8.0

- Examples.xcodeproj/project.pbxproj
- Podfile
- Podfile.lock
Updates to `ios-sdk-examples` for v5.9.0 of the Maps SDK.
> [WIP] Update for v5.9.0

- Examples.xcodeproj/project.pbxproj
- Podfile
- Podfile.lock
- README.md
Updates the project to use v6.1.0. Also adds a note to follow the installation guide for setting the project up via CocoaPods.
> Update for Maps SDK for iOS v6.1.0

- Examples.xcodeproj/project.pbxproj
- Podfile
- Podfile.lock
> Update to 6.2.0-beta.2

- Examples.xcodeproj/project.pbxproj
- Examples/Examples.h
- Examples/Examples.m
- Examples/ObjectiveC/Headers/ManageOfflineRegionsExample.h
- Examples/ObjectiveC/Headers/ManageOfflineRegionsExample.swift
- Examples/ObjectiveC/ManageOfflineRegionsExample.m
- Examples/Swift/ManageOfflineRegionsExample.swift
- Examples/Swift/OfflinePackExample.swift
Created an example for parity between iOS and Android regarding managing offline regions
> Pushing example to manage downloaded offline regions
