mapbox/ios-sdk-examples

Examples.xcodeproj/project.pbxproj
Examples/Examples.h
Examples/Examples.m
Examples/ObjectiveC/DDSCircleLayerExample.h
Examples/ObjectiveC/DDSCircleLayerExample.m
Examples/Swift/DDSCircleLayerExample.swift

Add data driven styling example using `MGLCircleStyleLayer`.
cc @jmkiley

Add DDS circle layer example

---

Examples/ObjectiveC/ClusteringExample.m
Examples/ObjectiveC/DDSCircleLayerExample.m
Examples/ObjectiveC/ShapeCollectionFeatureExample.m
Examples/Swift/ClusteringExample.swift
Examples/Swift/DDSCircleLayerExample.swift
Examples/Swift/ShapeCollectionFeatureExample.swift

Updates some recent examples’ tint colors to match their map styles. The main (and only) difference is that this colors the ℹ️ icon.
/cc @captainbarbosa

Set tint color to match map style

---

Examples.xcodeproj/project.pbxproj
Examples/Examples.h
Examples/Examples.m
Examples/ObjectiveC/DDSLayerSelectionExample.h
Examples/ObjectiveC/DDSLayerSelectionExample.m
Examples/Swift/DDSLayerSelectionExample.swift

We can possibly replace [select feature](https://www.mapbox.com/ios-sdk/examples/select-feature/) with this, since the feature selection example has a tile boundaries issue.
~- [x] Fix the flicker where you can see the previous state (did a different deselection approach):~
There's still a slight lag when you select one state, then deselect all states, then select another.

[Example] DDS Feature Selection

---

Examples.xcodeproj/project.pbxproj
Examples/ObjectiveC/DDSLayerSelectionExample.m
Examples/Swift/CustomCalloutViewExample.swift
Examples/Swift/OfflinePackExample.swift
Examples/Swift/RuntimeAddLineExample.swift
Examples/Swift/RuntimeAnimateLineExample.swift
ExamplesUITests/ExamplesUITests.m
Podfile
Podfile.lock

- Update to [Mapbox iOS SDK v3.5.1](https://github.com/mapbox/mapbox-gl-native/releases/tag/ios-v3.5.1).
- Manually rename `MGLStyleConstantValue ` to `MGLConstantStyleValue`, as the compatibility alias crashes Swift. (https://github.com/mapbox/mapbox-gl-native/issues/8567)
- Take advantage of improved `MGLCalloutView` bridging in `mapView:calloutViewFor annotation:` delegate method. (https://github.com/mapbox/mapbox-gl-native/pull/8541)
- Silence a technically correct but harmless incompatible types warning. (https://github.com/mapbox/ios-sdk-examples/commit/4b7dc5d6b1e4c7f2aea86299d31b725391d151ea)
- Miscellaneous fixes for Xcode 8.3 and Swift 3.1 changes.
- Reenable CocoaPods stats. 💆
/cc @1ec5 @boundsj

Update to v3.5.1 and Xcode 8.3

---

Examples.xcodeproj/project.pbxproj
Examples/Info.plist
ExamplesTests/Info.plist
ExamplesUITests/Info.plist
fastlane/Fastfile

Not sure why this only started failing now, but specify a dummy `CURRENT_PROJECT_VERSION` (build version).

Fix automated TestFlight/fastlane builds

---

Examples/ObjectiveC/FillPatternExample.m

Fixes the fill pattern Objective-C example by adding an `autoresizingMask` to the map view.
**Before**
**After** ✨

Add resizing mask to Obj-C example

---

Examples/ObjectiveC/PointConversionExample.m
Examples/Swift/PointConversionExample.swift

Updates the tap gesture recognizer in the point conversion example, given https://github.com/mapbox/mapbox-gl-native/pull/7816 (and friends). Also cleans up various comments, formatting, and does some renaming.
/cc @jmkiley @captainbarbosa

Refactor tap gesture in point conversion example

---

Podfile
Podfile.lock

https://github.com/mapbox/mapbox-gl-native/releases/tag/ios-v3.6.2

Bump to Mapbox iOS SDK v3.6.2

---

Podfile
Podfile.lock

https://github.com/mapbox/mapbox-gl-native/releases/tag/ios-v3.6.4
/cc @captainbarbosa @jmkiley

Bump to Mapbox iOS SDK v3.6.4

---

Examples.xcodeproj/project.pbxproj

Sets the DocsCode targets to use Swift 4, like the rest of the project.
/cc @jmkiley

Consistify project settings for Swift 4, etc.

---

Examples/ObjectiveC/CustomStyleExample.m
Examples/Swift/CustomStyleExample.swift

Adds a link to the documentation for [obtaining style URLs](https://www.mapbox.com/help/define-style-url/) in the custom style example.

Clarify comment on custom style example

---

DocsCode/DDSCircleLayerTutorial/DDSCircleLayerTutorialViewController.h
DocsCode/DDSCircleLayerTutorial/DDSCircleLayerTutorialViewController.m
DocsCode/DDSCircleLayerTutorial/DDSCircleLayerTutorialViewController.swift
DocsCode/FirstStepsTutorial/FirstStepsTutorialViewController.m
DocsCode/FirstStepsTutorial/FirstStepsTutorialViewController.swift
DocsCode/Info.plist
DocsCode/NavigationTutorial/NavigationTutorialViewController.h
DocsCode/NavigationTutorial/NavigationTutorialViewController.m
DocsCode/NavigationTutorial/NavigationTutorialViewController.swift
Examples.xcodeproj/project.pbxproj
Podfile
Podfile.lock

Adds the code used for iOS tutorials from [mapbox.com/help/tutorials](mapbox.com/help/tutorials/) into the DocsCode target. This will be used for testing code snippets before being used in documentation on [mapbox.com/help](mapbox.com/help).

Add tutorial code from mapbox.com/help

---

DocsCode/NavigationTutorial/NavigationTutorialViewController.m
DocsCode/NavigationTutorial/NavigationTutorialViewController.swift
Podfile
Podfile.lock

This PR edits some of the code comments in the code for the [navigation tutorial](https://www.mapbox.com/help/ios-navigation-sdk/).
It also switches `mapView.userTrackingMode` to `mapView.setCenter` and corrects a spelling error or two.

Navigation tutorial edits

---

Examples/Files/third_party_vector_style.json
Examples/ObjectiveC/ThirdPartyVectorStyleExample.m
Examples/Swift/ThirdPartyVectorStyleExample.swift

Updates the third party vector source example to use Mapillary tiles instead of Mapzen tiles.

Update third party vector source example

---

Examples/ObjectiveC/DraggableAnnotationViewExample.m
Examples/Swift/DraggableAnnotationViewExample.swift

Adds haptic feedback to the drag-and-drop annotations example.
Caveat: ObjC lets us declare properties with potentially unavailable classes and then check availability before initialization, but Swift does not. So, the Swift version can’t follow Apple’s suggested best practice of reusing the feedback generator (but the ObjC version can and does).
More about feedback generators can be found [at Apple’s docs](https://developer.apple.com/documentation/uikit/uifeedbackgenerator).
/cc @captainbarbosa @jmkiley @1ec5

DraggableAnnotationView: add haptic feedback

---

Examples/ObjectiveC/AnimatedLineExample.m
Examples/Swift/AnimatedLineExample.swift

Switches from using `mapView:didFinishLoadingStyle:` to `mapViewDidFinishLoadingMap:`, the latter of which fires when the map is visually loaded (as opposed to when the style object is ready to manipulate).
/cc @lilykaiser

AnimatedLineExample: delay animation until map truly finishes loading

---

Examples/ObjectiveC/ClusteringExample.m
Examples/ObjectiveC/FeatureSelectionExample.m
Examples/ObjectiveC/PointConversionExample.m
Examples/ObjectiveC/SelectFeatureExample.m
Examples/ObjectiveC/WebAPIDataExample.m
Examples/Swift/ClusteringExample.swift
Examples/Swift/FeatureSelectionExample.swift
Examples/Swift/PointConversionExample.swift
Examples/Swift/SelectFeatureExample.swift
Examples/Swift/WebAPIDataExample.swift

Fixes #162 by adding missing gesture failure checks.
It’s always necessary to check if the map view will handle a tap gesture before an example does, otherwise it’s possible to, e.g., have a double tap on an annotation both zoom and select-then-deselect that annotation.
/cc @jmkiley @captainbarbosa @lilykaiser

Require map's gestures to fail before accepting our taps

---

DocsCode/NavigationTutorial/NavigationTutorialViewController.m
DocsCode/NavigationTutorial/NavigationTutorialViewController.swift
Examples.xcodeproj/project.pbxproj
Podfile
Podfile.lock

Added the navigation SDK tutorial back to the DocsCode target, undoing one of the changes described in https://github.com/mapbox/ios-sdk-examples/pull/143#issuecomment-381796510. Upgraded to navigation SDK v0.17.0-beta.1. ~~For now, that beta is on a branch; once mapbox/mapbox-navigation-ios#1336 is released, we can use a tag instead.~~
/cc @captainbarbosa @colleenmcginnis @friedbunny

Navigation SDK v0.17.0-beta.1

---

Examples/ObjectiveC/AnnotationViewExample.m

Partly addresses https://github.com/mapbox/mapbox-gl-native/issues/11756 (also added `rotatesToMatchCamera = YES` to test).
See also https://github.com/mapbox/mapbox-gl-native/pull/11817 for the associated change in mapbox-gl-native.

Switched to using bounds rather than frame for cornerRadius (as frame changes when rotated).

---

Examples/Swift/AnnotationViewExample.swift

We forgot about Swift in #174, so this brings those changes to the Swift version of AnnotationViewExample, too.
/cc @julianrex

AnnotationViewExample: bring frame→bounds changes to Swift, too

---

Examples/Examples.m
Examples/ExamplesTableViewController.m
Examples/Main.storyboard

Fixes https://github.com/mapbox/ios-sdk-examples/issues/179, also I made some improvements:
1. Added asserts to make sure we can find the class of examples does not exist during development.
2. Show the class name fo examples on subtitle label, so that developers could easily find the corresponding class.

Add swift entry and show class name

---

Examples.xcodeproj/project.pbxproj
Examples/ObjectiveC/AnimatedLineExample.m
Examples/ObjectiveC/AnnotationViewExample.m
Examples/ObjectiveC/BuildingLightExample.m
Examples/ObjectiveC/TestingSupport.h
Examples/ObjectiveC/TestingSupport.m
Examples/Testing Categories/AnimatedLineExample+UITesting.m
Examples/Testing Categories/AnnotationViewExample+UITesting.m
Examples/Testing Categories/BuildingLightExample+UITesting.m
Examples/Testing Categories/ForwardingMapViewDelegate.h
Examples/Testing Categories/ForwardingMapViewDelegate.m
ExamplesUITests/ExamplesUITests.m
Podfile.lock

In the following PR:
- I've tried to leave the examples untouched; any test related code is in an associated category.
- Communication to the host test is via notifications (or existence of UI elements, but non of these tests do that). To handle this, this code inserts a forwarding delegate to manage posting notifications.
- One issue is that this delegate is inserted in `viewWillAppear` implemented in the category - this is fine right now, as NONE of the examples currently implement it. But ideally there would be a better way to manage this. Thoughts?
- This just uses XCUITests, without any 3rd party dependencies. Ideally, we'd keep it like this.
- I rejigged the `testEveryExample` test to use `XCTActivity` so that the test report shows a clean list of tests. It means the implementation …

Initial XCUITest handling

---

Examples/ObjectiveC/SwitchStylesExample.m
Examples/Swift/SwitchStylesExample.swift

Closes https://github.com/mapbox/ios-sdk-examples/issues/210.
Notable changes:
- UISegmentedControl now has a background color and a tint color.
- Swapped Mapbox Dark for Satellite to better match with the color schemes of the other styles and colors used for the UISegmentedControl.
- Stopped resizing the UISegmentedControl when rotated.
Finding colors that matched yet contrasted enough was difficult for my non-designer self, so suggestions welcome. I would have liked to customize only the text color of each UISegment label but it doesn't seem there is a way to do this without introducing more complexity to the example.

Improve UISegment control style and layout for SwitchStyles example

---

Podfile
Podfile.lock

A branch to test `ios-v4.4.0` pre-releases in (and eventually merge, after we’re finished).
/cc @mapbox/maps-ios

Update to maps SDK 4.4.0

---

Examples.xcodeproj/project.pbxproj

Ensure the access token build phase takes precedence over the standard Info.plist copying step under the new build system in Xcode 10, per the updated [private access token documentation](https://www.mapbox.com/help/ios-private-access-token/).
/cc @captainbarbosa @friedbunny

Ensure build phase inserts access token

---

Examples.xcodeproj/xcshareddata/xcschemes/Examples.xcscheme
ExamplesUITests/ExamplesUITests.m

- Fixes #217 by ~splitting `testEveryExample` into `testEveryObjCExample` and `testEverySwiftExample`~ making `testEveryExample` run both Swift and Obj-C examples.
- Puts a bandaid over #221 by disabling the [flapping](https://app.bitrise.io/build/056f8df40469d0e3) ~`testAnimatedLineExample`~ individual tests.
/cc @mapbox/maps-ios

Run testEveryExample against both Obj-C and Swift again

---

Examples/ObjectiveC/ImageSourceExample.m
Examples/ObjectiveC/SatelliteStyleExample.m
Examples/Swift/ImageSourceExample.swift
Examples/Swift/SatelliteStyleExample.swift

Just some minor edits to `ImageSourceExample` and `SatelliteStyleExample` that occurred to me as I was researching another issue.
- Updates comments and keeps them consistent across objc/swift.
- Simplifies image loading.
- Removes some very deep indentation.
/cc @jmkiley @captainbarbosa

ImageSourceExample: make objc/swift consistent; simplify

---

Podfile
Podfile.lock

Upgraded to navigation SDK v0.25.0. Upgrading MapboxDirections.swift to v0.25._x_ produced some Objective-C compiler warnings, which are fixed in mapbox/MapboxDirections.swift#317.
/cc @frederoni

Navigation SDK v0.25.0

---

Examples/ObjectiveC/ClusteringExample.m
Examples/Swift/ClusteringExample.swift

~~This PR is waiting for https://github.com/mapbox/mapbox-gl-native/pull/12952 to land in mapbox-gl-native~~
Updates cluster example to demostrate new cluster APIs.
Single tap on a cluster to see cluster information.
Double tap on a cluster to zoom into that cluster so that it expands to its children.

Updates cluster example for new cluster APIs

---

Examples/ObjectiveC/FeatureSelectionExample.m
Examples/Swift/FeatureSelectionExample.swift

Fixes an issue introduced in [#249](https://github.com/mapbox/ios-sdk-examples/pull/249/commits/fd73525217773377393b9a883267ad366f278b5b) where a layer identifier was updated for streets-v8 without regard to backwards compatibility. Since 4.7.1 temporarily pulled v8 styles back as the defaults in the Maps SDK, this fixes a crash on every version except 4.7.0 and 4.8.0.
/cc @captainbarbosa @1ec5 @julianrex @fabian-guerra @zugaldia

FeatureSelectionExample: Add fallback layer for older streets sources

---

DocsCode/NavigationTutorial/NavigationTutorialViewController.m
DocsCode/NavigationTutorial/NavigationTutorialViewController.swift

Rewrote comments associated with the lines that set `coordinateAccuracy`. These comments were based on [a MapboxDirections.swift documentation comment](https://github.com/mapbox/MapboxDirections.swift/blob/c350b60489c33845551cf0163a5481d32c940479/MapboxDirections/MBWaypoint.swift#L16) but somehow got mangled.
Fixes #265.
/cc @samfader

Rewrite comment explaining coordinate accuracy

---

Podfile
Podfile.lock

Upgraded to map SDK v4.7.1, navigation SDK v0.28.0, and SwiftLint v0.30.1.
/cc @JThramer @friedbunny

Map SDK v4.7.1, navigation SDK v0.28.0, SwiftLint v0.30.1

---

Examples.xcodeproj/project.pbxproj
Examples/Examples.h
Examples/Examples.m
Examples/ObjectiveC/Headers/LabelPlacementExample.h
Examples/ObjectiveC/LabelPlacementExample.m
Examples/Swift/LabelPlacementExample.swift

Example for label collision placement.

[ios] Add example for label placement.

---

Examples/ObjectiveC/ClusteringExample.m

Fixes #276 
Used [`%zd`](https://useyourloaf.com/blog/format-string-issue-using-nsinteger/) to address the warnings.

Address ClusteringExample NSUInteger warnings

---

Examples/ObjectiveC/ClusteringExample.m
Examples/Swift/ClusteringExample.swift

Allow icon overlap for unclustered layer in ClusteringExample

---

Examples.xcodeproj/project.pbxproj
Gemfile
Gemfile.lock
Podfile
Podfile.lock
fastlane/Fastfile

~Includes #278~, as we need that and it can’t be merged to `master` until we’re finished with that release.

Update for Maps SDK 4.11.0 (release-mojito)

---

Examples/ObjectiveC/CustomCalloutView.m
Examples/Swift/CustomCalloutView.swift

Custom `MGLCalloutView` callouts should call `calloutViewWillAppear` / `calloutViewDidAppear` - without this, callout views can be out of synch (due to the toggling of `presentsWithTransaction:` introduced in https://github.com/mapbox/mapbox-gl-native/pull/14307).

Custom callout presentation should call delegate methods.

---

Examples/Swift/CustomCalloutView.swift
Examples/Swift/LabelPlacementExample.swift
Examples/Swift/MissingIconsExample.swift
Examples/Swift/TextFormattingExample.swift
Examples/Swift/UserTrackingModesExample.swift

Fixes almost all of the Swiftlint warnings noted from https://github.com/mapbox/ios-sdk-examples/issues/302, with the exception of the `todo` warnings - these should be addressed by https://github.com/mapbox/ios-sdk-examples/issues/304 & #305.
cc @fabian-guerra

Clean up Swiftlint warnings

---

Examples.xcodeproj/project.pbxproj
Podfile
Podfile.lock

Upgraded to navigation SDK v0.34.0, rolling back the temporary changes in #301, now that the navigation SDK depends on map SDK v5.0._x_.
/cc @mapbox/navigation-ios @mapbox/maps-ios

Navigation SDK v0.34.0

---

Examples.xcodeproj/project.pbxproj
Podfile
Podfile.lock

This reverts commit 5eeca0f1b93d54e42aab2b06b8c0162d9b0f5ae3 from #222, bringing back the DocsCode target, and upgrades to navigation SDK v0.35.0, which is compatible with map SDK versions from 5.1.0 up to (but not including 6.0.0).
/cc @mapbox/navigation-ios @friedbunny

Revert "Disable incompatible Nav SDK and DocsCode target"

---

Examples/ObjectiveC/CustomCalloutViewExample.m
Examples/ObjectiveC/DefaultCalloutExample.m
Examples/ObjectiveC/WebAPIDataExample.m
Examples/Swift/CustomCalloutViewExample.swift
Examples/Swift/DefaultCalloutExample.swift
Examples/Swift/WebAPIDataExample.swift

Per https://github.com/mapbox/mapbox-gl-native/pull/14381.
/cc @captainbarbosa

Update to new completionful methods in maps 5.2.0

---

Examples.xcodeproj/xcshareddata/xcschemes/Examples.xcscheme
README.md
codecov.yml

This adds a code coverage badge and enables code coverage on this repo. Currently ignores tests and the [Testing Categories](https://github.com/mapbox/ios-sdk-examples/tree/master/Examples/Testing%20Categories) when generating code coverage.

Enable code coverage, add code coverage & bitrise badges

---

Examples/ObjectiveC/AnimatedLineExample.m

Fixes https://github.com/mapbox/ios-sdk-examples/issues/242.

Fix timer not firing in AnimatedLineExample.

---

Examples/ExamplesTableViewController.m
Examples/ObjectiveC/AnnotationViewsAndImagesExample.m
Examples/ObjectiveC/BuildingLightExample.m
Examples/ObjectiveC/ClusteringExample.m
Examples/ObjectiveC/CustomCalloutView.m
Examples/ObjectiveC/DDSCircleLayerExample.m
Examples/ObjectiveC/HeatmapExample.m
Examples/ObjectiveC/LineStyleLayerExample.m
Examples/ObjectiveC/OfflinePackExample.m
Examples/ObjectiveC/StaticSnapshotExample.m
Examples/ObjectiveC/SwitchStylesExample.m
Examples/ObjectiveC/TextFormattingExample.m
Examples/ObjectiveC/UserLocationAnnotationExample.m
Examples/ObjectiveC/UserTrackingModesExample.m
Examples/ObjectiveC/WebAPIDataExample.m

Fixes a variety of `implicit conversion loses floating-point precision: 'double' to 'CGFloat' (aka 'float') [-Wimplicit-float-conversion]` warnings when building for release.
/cc @captainbarbosa

Fix floating point precision warnings

---

Examples/ObjectiveC/OfflinePackExample.m
Examples/Swift/OfflinePackExample.swift

Fixes #340. Should let UI tests be marginally better performant/more reliable, since offline pack downloads won’t spill over outside the relevant view controller.
/cc @captainbarbosa @jmkiley

OfflinePackExample: limit impact of offline pack downloads on the app

---

Examples/Examples.m

Moves the unfinished examples from #303, #304, #305 to a ‘Works in progress’ category at the bottom of the table view.
Also fixes a variety of formatting issues and typos.
/cc @fabian-guerra @jmkiley @captainbarbosa

Move unfinished examples to 'Works in progress' category

---

Examples/Examples.m
Examples/ExamplesTableViewController.m
Examples/Main.storyboard
ExamplesUITests/ExamplesUITests.m

Some really quick changes to the table view’s appearance while we consider what the next version of this app will be.
- Adopts the modern `UITableViewStyleInsetGrouped` appearance, which is new in iOS 13 but is generally backwards compatible.
- Fixes #338 by adding support for dark mode, mainly by using semantic colors.
- Adds basic support for dynamic type and multiline wrapping of long strings.
| ![Simulator Screen Shot - iPhone X - 2019-09-07 at 00 00 58](https://user-images.githubusercontent.com/1198851/64471182-d5e1de00-d102-11e9-8e84-55142c81fca0.png) | ![Simulator Screen Shot - iPhone X - 2019-09-06 at 23 15 15](https://user-images.githubusercontent.com/1198851/64470804-03785880-d0fe-11e9-8bf6-13343d8ca7cd.png) | ![Simulator Screen Shot - iPhone X - 2019-09-07 at 00 06 …

Modernize table view appearance

---

DEPLOYMENT.md

Update the docs in the wake of https://github.com/mapbox/ios-sdk-examples/pull/339.
/cc @mapbox/maps-ios

[testflight] Add automatic CI deployment instructions

---

Examples/ExamplesContainerViewController.m

Fixes #361 by removing [`UINavigationController.hidesBarsWhenVerticallyCompact`](https://developer.apple.com/documentation/uikit/uinavigationcontroller/1621869-hidesbarswhenverticallycompact), which appears to have issues in iOS 13.
/cc @captainbarbosa @jmkiley

Work-around iOS 13 navigation controller rotation bug

---

Examples.xcodeproj/project.pbxproj
Examples/Examples.h
Examples/Examples.m
Examples/ObjectiveC/ShapeAnnotationsExample.h
Examples/ObjectiveC/ShapeAnnotationsExample.m
Examples/Swift/ShapeAnnotationsExample.swift

Adds a new example to showcase how to add three types of annotations to one map, all with callouts:
This example was made in part to subsume `DefaultCalloutExample`,  `PolygonAnnotationExample`, and `LineAnnotationGeoJSONExample` (although this example doesn't add data from parsed GeoJSON, we have other examples of this already).

Add ShapeAnnotationsExample

---

DocsCode/DDSCircleLayerTutorial/DDSCircleLayerTutorialViewController.m
DocsCode/DDSCircleLayerTutorial/DDSCircleLayerTutorialViewController.swift
DocsCode/FirstStepsTutorial/FirstStepsTutorialViewController.m
DocsCode/FirstStepsTutorial/FirstStepsTutorialViewController.swift

We don't need these comments anymore. This PR removes them so the code we display in tutorials is cleaner. 💅

Remove example transfuser comments in tutorial demos

---

DEPLOYMENT.md
README.md

Edits some links to refer to the new `main` primary branch!

Update links to reference "main" branch

---

Examples.xcodeproj/project.pbxproj
Podfile
Podfile.lock

Updates to Mapbox Maps SDK for iOS [6.3.0](https://github.com/mapbox/mapbox-gl-native-ios/releases/tag/ios-v6.3.0).

Update to Mapbox v6.3.0
